"""Added status table to control status of project

Revision ID: 358d487c0987
Revises: cd72928eb8b6
Create Date: 2026-03-05 10:57:39.784371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358d487c0987'
down_revision = 'cd72928eb8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('handed_in', sa.Boolean(), nullable=True),
    sa.Column('handed_in_at', sa.Date(), nullable=True),
    sa.Column('signed', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
