version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mohamad
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: