"""Corrected typo in address_id

Revision ID: 206e40ff7225
Revises: 9291c851a4c1
Create Date: 2025-12-02 15:38:03.548445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206e40ff7225'
down_revision = '9291c851a4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('orders_addres_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])
        batch_op.drop_column('addres_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addres_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_addres_id_fkey'), 'address', ['addres_id'], ['id'])
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
