"""Increase password field length

Revision ID: 82da732d580c
Revises: 165ea2fe2a4a
Create Date: 2025-11-11 15:07:21.675713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82da732d580c'
down_revision = '165ea2fe2a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
