"""Changed signup logic to include magiclinks instead of passwords

Revision ID: 8a93eb9cfb53
Revises: 16329ae493a2
Create Date: 2025-11-21 19:06:44.718748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a93eb9cfb53'
down_revision = '16329ae493a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
