"""Added order_items table, total column, address_id to orders

Revision ID: 9291c851a4c1
Revises: e324a2554e2a
Create Date: 2025-12-02 11:03:01.084802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9291c851a4c1'
down_revision = 'e324a2554e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addres_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_constraint(batch_op.f('orders_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'address', ['addres_id'], ['id'])
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_item_id_fkey'), 'items', ['item_id'], ['id'])
        batch_op.drop_column('total')
        batch_op.drop_column('addres_id')

    op.drop_table('order_items')
    # ### end Alembic commands ###
