"""Created separate status table

Revision ID: f65aaf67b32e
Revises: ab4d17d50730
Create Date: 2025-12-10 11:45:31.252535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65aaf67b32e'
down_revision = 'ab4d17d50730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('prepared', sa.Boolean(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('underway', sa.Boolean(), nullable=True),
    sa.Column('underway_at', sa.DateTime(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipped')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipped', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.drop_table('order_status')
    # ### end Alembic commands ###
